/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SeQiaM4ykc3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { useState } from "react"
import { format } from "date-fns"

import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Switch } from "@/components/ui/switch"
import { Button } from "@/components/ui/button"
import { CardOption } from "@/components/ui/card-option"
import { VenueCardOption } from "@/components/ui/venue-card-option"
import { UsersIcon, CheckIcon, CalendarDaysIcon, UserIcon, ChevronDownIcon, ClockIcon, ArrowRightIcon } from "@/components/icons"
import { DatePicker } from "@/components/ui/date-picker"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"


  export function BookingWidget() {
    const [guests, setGuests] = useState('');
    const [date, setDate] = useState('');
    const [time, setTime] = useState('');
    const [duration, setDuration] = useState('');
    const [isMultiDay, setMultiDay] = useState(false);
    const [tableSetup, setTableSetup] = useState('Boardroom');
    const [venue, setVenue] = useState('Blossom Private Space');
  
    const isStep1Valid = () => {
      return guests > 0 && date !== '' && time !== '' && duration !== '';
    }
    
  return (
    <div className="flex justify-center space-x-8 overflow-visible">
      <div className="w-3/4 p-8 mt-8">
        <h2 className="text-2xl font-bold text-center">Let's get you started</h2>
        <p className="text-center text-muted-foreground mt-6">When and with how many people will you meet?</p>
        <div className="space-y-4 mt-8 grid grid-rows-2 justify-center">
          <div className="grid grid-cols-2 space-x-4">
            <div className="max-w-[330px] w-full">
              <Label htmlFor="guests">Number of guests</Label>
              <div className="relative mt-2">
                <Input className="pr-8" type="number" id="guests" placeholder="12" max="22" value={guests} onChange={(e) => setGuests(e.target.value)} />
                <UserIcon className="absolute right-2 top-1/2 transform -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              </div>
            </div>
            <div className="max-w-[330px] w-full">
              <Label htmlFor="date">When is it happening</Label>
              <div className="relative mt-2">
                <DatePicker date={date} setDate={setDate} />
                {/* <Input type="date" id="date" value={date} onChange={(e) => setDate(e.target.value)} />
                <CalendarDaysIcon className="absolute right-2 top-1/2 transform -translate-y-1/2 h-5 w-5 text-muted-foreground" /> */}
              </div>
            </div>
          </div>
          <div className="grid grid-cols-2 space-x-4 items-end">
            <div className="flex-1 max-w-[330px]">
              <Label htmlFor="time">Time of arrival</Label>
              <div className="relative mt-2">
                <Input type="time" id="time" placeholder="09:00 am" value={time} onChange={(e) => setTime(e.target.value)} />
                <ClockIcon className="absolute right-2 top-1/2 transform -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <Switch id="multi-day" checked={isMultiDay} onClick={(e) => setMultiDay(e.target.checked)} />
              <Label htmlFor="multi-day">Multi day event</Label>
            </div>
          </div>
        </div>
        <div className="mt-12 space-y-8 flex flex-col items-center">
          <h3 className="text-center text-lg font-bold">
            Event Duration <span className="text-sm text-red-400">(required)</span>
          </h3>
          <div className="flex space-x-4 mt-8">
            <CardOption title="8 Hours" description="Includes Post-its, markers & Presentation screen." onClick={() => setDuration(8)} duration={duration} value={8} />
            <CardOption title="4 Hours" description="Includes Post-its, markers & Presentation screen." onClick={() => setDuration(4)} duration={duration} value={4} />
            <CardOption title="Hourly rate" description="Includes Post-its, markers & Presentation screen." onClick={() => setDuration(1)} duration={duration} value={1} />
          </div>
        </div>
        <div className="mt-12 space-y-8 flex flex-col items-center">
          <h3 className="text-lg font-bold text-center">
            Venue Preference <span className="text-muted-foreground">(optional)</span>
          </h3>
          <div className="flex items-center space-x-2 mt-4">
          <Select onValueChange={(value) => setTableSetup(value)} defaultValue="Boardroom">
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder="Boardroom Setup" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="Boardroom">Boardroom</SelectItem>
            <SelectItem value="U-Shape">U-Shape</SelectItem>
            <SelectItem value="Classroom">Classroom</SelectItem>
            <SelectItem value="Intimate">Intimate - no tables</SelectItem>
          </SelectContent>
        </Select>

          </div>
          <div className="grid grid-cols-2 gap-4 mt-4">
            <VenueCardOption
              venue_name={"Blossom Private Space"}
              venue_description={"With a spacious garden can host teams up to..."}
              image_url={"/placeholder.svg"}
              capacity={22}
              area={70}
              isSelected={venue === "Blossom Private Space"}
              onClick={() => setVenue("Blossom Private Space")}
            />
            <VenueCardOption
              venue_name={"Aurora Private Space"}
              venue_description={"With a spacious garden can host teams up to..."}
              image_url={"/placeholder.svg"}
              capacity={22}
              area={70}
              isSelected={venue === "Aurora Private Space"}
              onClick={() => setVenue("Aurora Private Space")}
            />
          </div>
        </div>
        <div className="mt-12 space-y-8 flex flex-col items-center">
          <Button className="mt-8" disabled={!isStep1Valid()}>Add event options <ArrowRightIcon className="ml-2 h-5 w-5 text-white" /></Button>
        </div>
      </div>
      <div className="w-1/4 p-8 bg-gray-50 overflow-visible mt-0 rounded-md">
        <div className="flex flex-col sticky top-10 space-x-2">
          <h3 className="text-lg font-bold">Overview</h3>
          <div className="mt-4 space-y-6">

              <div className="flex items-center space-x-2">
                <CalendarDaysIcon className="h-5 w-5 text-muted-foreground" />
                <p className="text-sm">
                  {date ? format(date, "PPP") : "Pick a date"}
                </p>
              </div>
              <div className="flex items-center space-x-2">
                <UsersIcon className="h-5 w-5 text-muted-foreground" />
                <p className="text-sm">{guests} { guests > 0 ? "people" : "Select Number Guests"}</p>
              </div>
            <div className="flex items-center space-x-2">
              <ClockIcon className="h-5 w-5 text-muted-foreground" />
              <p className="text-sm">
                {time ? "Arrival at " + time : "Select Time"}
              </p>
            </div>
            <div className="mt-4 space-y-2">
              <h4 className="text-sm font-bold">Venue Preference</h4>
              <p className="text-sm">
                {venue} - {tableSetup}
              </p>
            </div>
            <div className="mt-4 space-y-2">
              <h4 className="text-sm font-bold">Always included</h4>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-muted-foreground" />
                <p className="text-sm">Conference system</p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-muted-foreground" />
                <p className="text-sm">Presentation screen</p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-muted-foreground" />
                <p className="text-sm">Post it's & markers</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
